### ISSUE TITLE
Unclear how to use the package with a deep hierarchy

### ISSUE THREAD

**Issue by MaxKHK** [globality-corp/sklearn-hierarchical-classification#11]
Hi!

Thank you for the package, it is really good!

I have an issue. provided example has a very small depth of the hierarchy (classify_digits.py). It has just ROOT node and 2 levels underneath. I am not certain how to make the hierarchy deeper?

I tried to use the approach:

{ROOT: [A, B], A:{A1:[1,2], A2:[3,4]}, B: {B1:[5,6], B2: [7,8]} but it doesn't seem to work (classifier terminates without actually fitting)

**Comment by bluetyson** [comment]
Yes, I get the same thing.

**Comment by bluetyson** [comment]
Apparently this works :
class_hierarchy6 = {
        ROOT: ["A", "B"],
        "A": ["A1","A2"],
        "B": ["B1", "B2", "B3"],
        "A1": [1],
        "A2": [7],
        "B1": [3],
        "B2": [8],
        "B3": [9],
    }

**Comment by adamhadani** [comment]
@MaxKHK @bluetyson  - I've updated the classify_digits.py example to reflect usage for deeper hierarchy, check it out.

Main confusion was that the example was mixing different types of labels (ints and strings) as part of the hierarchy definition. I simplified it to using a uniform typing (all strings), and things "just work" that way.

I did notice that using a mix of ints and strings leads to some errors, most likely due to how the base estimators handle such a mix (e.g. converting implicitly so that everything has one type). I suggest to just use a single type when defining the training/evaluation data (`y`).
