### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mbhatt1** [globality-corp/sklearn-hierarchical-classification#8]
Trying to use https://rasbt.github.io/mlxtend/user_guide/classifier/StackingClassifier/ as the local node classifier together with the hierarchical classifier API.  If I use the StackingClassifier class it keeps telling me that 

```
'StackingClassifier' object has no attribute 'classes_'
```

if I use the StackingCVClassifier then it keeps telling me that
```
TypeError: only integer scalar arrays can be converted to a scalar index
Please check that X and yare NumPy arrays. If X and y are lists of lists,
try passing them as numpy.array(X) and numpy.array(y).
```
I did pass arrays into the classifier and not dataframes. Could someone help me please?

**Comment by adamhadani** [comment]
@mbhatt1 :

sklearn classifiers typically assign a `self.classes_` parameter as part of the `fit()` call.
In the case of a meta-classifier (e.g. StackingClassifier), it seems this is not done at the root classifier level, but is delegated to the individual (stacked) classifiers.

This attribute is required by this package ([here](https://github.com/globality-corp/sklearn-hierarchical-classification/blob/develop/sklearn_hierarchical_classification/classifier.py#L437) in order to actually map from individual classifiers (nodes) predicted class to which node should be 'visited' next.

I suggest taking up this issue with the `mlxtend` people behind StackingClassifier; one potential solution is to have the StackingClassifier define a property getter returning `classes_` or otherwise computing it based on the individual classifiers trained as part of the stacking, in the fit(). Then, everything should 'just work'.

**Comment by mbhatt1** [comment]
Thank you. I understand :)
